name: Build and Deploy to AKS

on:
  push:
    branches:
      - main  # Triggers workflow on push to 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner

    steps:
    # Checkout your repository's code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Log in to Azure using the GitHub secret AZURE_CREDENTIALS
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Set up Docker Buildx (for building and pushing Docker images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to Azure Container Registry
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: demoregistryaks1.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build and push the Docker image to ACR
    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: demoregistryaks1.azurecr.io/my-node-app:latest

    # Set up kubectl tool
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Get AKS credentials to access the cluster
    - name: Get AKS credentials
      run: az aks get-credentials --resource-group vnet-aks-demo-rg --name demo-aks-public2

    # Deploy application to AKS using kubectl
    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

