name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry (ACR)
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image to ACR
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-node-app:latest .
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-node-app:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure KUBECONFIG from Secret
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Deploy to AKS using kubectl
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
