name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry (ACR)
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-node-app:latest .
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-node-app:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Decode and Set KUBECONFIG
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

        # Optional: validate connectivity
        kubectl --kubeconfig=$PWD/kubeconfig cluster-info

    - name: Deploy to AKS
      run: |
        kubectl --kubeconfig=$PWD/kubeconfig apply -f k8s/deployment.yaml
        kubectl --kubeconfig=$PWD/kubeconfig apply -f k8s/service.yaml
